/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class steambot_SteamBotJNI */

#ifndef _Included_steambot_SteamBotJNI
#define _Included_steambot_SteamBotJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     steambot_SteamBotJNI
 * Method:    Initialise
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_steambot_SteamBotJNI_Initialise
  (JNIEnv *, jobject);

/*
 * Class:     steambot_SteamBotJNI
 * Method:    IsInitialised
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_steambot_SteamBotJNI_IsInitialised
  (JNIEnv *, jobject, jlong);

/*
 * Class:     steambot_SteamBotJNI
 * Method:    SetServerInformation
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_steambot_SteamBotJNI_SetServerInformation
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     steambot_SteamBotJNI
 * Method:    GetPlayerCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_steambot_SteamBotJNI_GetPlayerCount__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     steambot_SteamBotJNI
 * Method:    GetPlayerCount
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_steambot_SteamBotJNI_GetPlayerCount__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     steambot_SteamBotJNI
 * Method:    GetPlayers
 * Signature: (J)[Lsteambot/SteamBotJNI/SteamPlayer;
 */
JNIEXPORT jobjectArray JNICALL Java_steambot_SteamBotJNI_GetPlayers__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     steambot_SteamBotJNI
 * Method:    GetPlayers
 * Signature: (JJ)[Lsteambot/SteamBotJNI/SteamPlayer;
 */
JNIEXPORT jobjectArray JNICALL Java_steambot_SteamBotJNI_GetPlayers__JJ
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
